spring:
  application:
    name: Car-Search-Service

  redis:
    host: localhost
    port: 6379

  cloud:
    client:
      hostname: localhost

server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      inventoryCB:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

  retry:
    instances:
      inventoryRetry:
        maxAttempts: 3
        waitDuration: 1s
